dataloader:
  train_ratio: 0.8
  batch_size: 128
  num_workers: 4
train:
  seed: 42
  n_epoch: 1000
  save_interval: 5
  gen_lr: 0.0001
  dis_lr: 0.0001
model:
  noise_dim: 100
  label_dim: 10
  img_dim: 784
  